name: dashboard
pre_window: export TERRAFORM_TARGET=localhost; clear
root: /stemn/stemn-backend/infrastructure/development-environment

windows:
  - terminal:
      layout: tiled
      panes:
        - yarn logs
        - yarn ctop
        - cd ../..; clear; source ~/.zshenv
        - s-tui
  - jest:
      layout: main-vertical
      panes:
        - yarn tmux:test:watch:attach
        - yarn logs:jest
        - yarn start:mongo:shell
  - pipelines:
      layout: even-vertical
      panes:
        - yarn ctop:pipelines
        - yarn logs:pipelines:server
        - yarn logs:pipelines:containers
  - continuous-integration:
      layout: tiled
      panes:
        - yarn logs:abstruse
        - yarn ctop:abstruse
        - yarn logs:abstruse:containers
        - yarn htop
  - ingress:
      layout: tiled
      panes:
        - yarn logs:ingress
  - frontend:
      layout: even-horizontal
      panes:
        - yarn tmux:build:frontend:website:attach
        - yarn tmux:build:frontend:desktop:electron:attach
        - yarn tmux:build:frontend:desktop:renderer:attach
  - storage:
      layout: even-vertical
      panes:
        - yarn logs:mongodb
        - yarn logs:redis
  - kubernetes:
      layout: even-horizontal
      panes:
        - yarn tmux:kubebox:attach
        - yarn logs:kubernetes
