language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script: packer/scripts/build.sh

deploy:
  on:
    branch: master
  provider: script
  script: terraform/scripts/recycle.sh
