language: sh

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

git:
  depth: false
  quiet: true
  
script:
  - docker/scripts/build.sh
  - packer/scripts/build.sh

deploy:
  on:
    branch: master
  provider: script
  script:
    - terraform/scripts/restart.sh
